### ISSUE TITLE
全局参数配置问题

### ISSUE THREAD

**Issue by bigbugbean** [SpringForAll/spring-boot-starter-swagger#29]
全局参数不配置会抛空指针异常

**Comment by dyc87112** [comment]
@renlulu 看看？我记得好像处理过

**Comment by dyc87112** [comment]
@bigbugbean 是用的1.5.0吗？

**Comment by bigbugbean** [comment]
嗯，是1.5




------------------ 原始邮件 ------------------
发件人: "程序猿DD-翟永超";<notifications@github.com>;
发送时间: 2017年10月20日(星期五) 下午4:39
收件人: "SpringForAll/spring-boot-starter-swagger"<spring-boot-starter-swagger@noreply.github.com>;
抄送: "杜国铭"<du.guoming@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [SpringForAll/spring-boot-starter-swagger] 全局参数配置问题 (#29)




@bigbugbean 是用的1.5.0吗？

**Comment by yuansongming** [comment]
我也遇到了，
依赖：compile("com.spring4all:spring-boot-starter-swagger:1.5.0.RELEASE")
----------------------------------------------------------------------------------------------------
    private List<Parameter> buildGlobalOperationParametersFromSwaggerProperties(
            List<SwaggerProperties.GlobalOperationParameter> globalOperationParameters) {
        List<Parameter> parameters = Lists.newArrayList();
        **// 此处未对globalOperationParameters作null判断，全局参数为null的时候出现异常**
        for (SwaggerProperties.GlobalOperationParameter globalOperationParameter : globalOperationParameters) {
            parameters.add(new ParameterBuilder()
                    .name(globalOperationParameter.getName())
                    .description(globalOperationParameter.getDescription())
                    .modelRef(new ModelRef(globalOperationParameter.getModelRef()))
                    .parameterType(globalOperationParameter.getParameterType())
                    .required(Boolean.parseBoolean(globalOperationParameter.getRequired()))
                    .build());
        }
        return parameters;
    }
----------------------------------------------------------------------------------------------------
Caused by: java.lang.NullPointerException: null
	at com.spring4all.swagger.SwaggerAutoConfiguration.buildGlobalOperationParametersFromSwaggerProperties(SwaggerAutoConfiguration.java:174) ~[spring-boot-starter-swagger-1.5.0.RELEASE.jar:na]
	at com.spring4all.swagger.SwaggerAutoConfiguration.createRestApi(SwaggerAutoConfiguration.java:91) ~[spring-boot-starter-swagger-1.5.0.RELEASE.jar:na]
	at com.spring4all.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$738505f9.CGLIB$createRestApi$1(<generated>) ~[spring-boot-starter-swagger-1.5.0.RELEASE.jar:na]
	at com.spring4all.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$738505f9$$FastClassBySpringCGLIB$$c10813c2.invoke(<generated>) ~[spring-boot-starter-swagger-1.5.0.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at com.spring4all.swagger.SwaggerAutoConfiguration$$EnhancerBySpringCGLIB$$738505f9.createRestApi(<generated>) ~[spring-boot-starter-swagger-1.5.0.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 19 common frames omitted

**Comment by dyc87112** [comment]
1.5.1修复
